# Generated by Django 3.1.7 on 2021-03-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=50, verbose_name='Service ID')),
                ('consumer', models.CharField(max_length=50, verbose_name='Consumer ID')),
                ('proxy', models.IntegerField(default=0, verbose_name='Proxy')),
                ('gateway', models.IntegerField(default=0, verbose_name='Gateway')),
                ('request', models.IntegerField(default=0, verbose_name='Request')),
                ('line', models.TextField(verbose_name='Original Log Line')),
                ('started_at', models.CharField(max_length=200, verbose_name='Started At')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
